apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-processor
  labels:
    helm.sh/chart: rabbitmq-{{ .Values.version }}
    app.kubernetes.io/name: processor
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: rabbitmq-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
