apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  type: NodePort
  selector:
    app: kibana
    release: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: elastic-search-service
spec:
  type: NodePort
  selector:
    app: elasticsearch-master
    chart: elasticsearch
    release: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30002
