apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-producer
  labels:
    app: rabbitmq-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-producer
  template:
    metadata:
      labels:
        app: rabbitmq-producer
    spec:
      automountServiceAccountToken: false
      containers:
        - name: rabbitmq-producer
          image: "localhost:5001/rabbitmq-producer:{{ .Values.version }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/vertx-cache
              name: vertx-cache
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 1m
              memory: 100Mi
              ephemeral-storage: 1Mi
            limits:
              cpu: "1"
              memory: 256Mi
              ephemeral-storage: 100Mi
      volumes:
        - name: vertx-cache
          emptyDir: { }
