apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-producer-service
spec:
  type: NodePort
  selector:
    app: rabbitmq-producer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
