apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-producer
  labels:
    helm.sh/chart: rabbitmq-{{ .Values.version }}
    app.kubernetes.io/name: producer
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: producer
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /q/metrics
      interval: 30s
