apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-producer
  labels:
    helm.sh/chart: rabbitmq-{{ .Values.version }}
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: Helm
    app: rabbitmq-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-producer
  template:
    metadata:
      labels:
        app: rabbitmq-producer
    spec:
      automountServiceAccountToken: false
      containers:
        - name: rabbitmq-producer
          image: "localhost:5001/rabbitmq-producer:{{ .Values.version }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/vertx-cache
              name: vertx-cache
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "1m"
              memory: "128Mi"
              ephemeral-storage: "1Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
              ephemeral-storage: "100Mi"
      volumes:
        - name: vertx-cache
          emptyDir: { }
